package com.xd.commander.aku.constants;

/**
 * Created by Administrator on 2017/4/12.
 */

public final class Constants {
    /**
     * 静态常量
     */

    public final static String URL = "https://android-arsenal.com/";
    public final static String GitHub = "https://api.github.com/";
    public final static String GitHubSource = "https://codeload.github.com/";
    public final static String GitHubMarkdown = "https://raw.githubusercontent.com/";
    public final static String Key_Bugly = "8abad09569";
    public final static String Key_Bmob = "fc845d2c89dcdab10aad9b17d4805f79";
    public final static String Page = "page";
    public final static String Sort = "vector_bmnavi_sort";
    public final static String Category = "category";
    public static final String NETWORK_DETECTOR = "com.xd.commander.aku.DATA_AVAILABLE";
    public static final String DATA_AVAILABLE = "isDataAvailable";
    public static final String ON_SYNC = "onSync";
    public static final String[] data = { "2D Engines",
            "3D Engines",
            "9-Patch",
            "Action Bars",
            "Activities",
            "ADB",
            "Advertisements",
            "Analytics",
            "Animations",
            "ANR",
            "AOP",
            "API",
            "APK",
            "APT",
            "Architecture",
            "Audio",
            "Autocomplete",
            "Background Processing",
            "Backward Compatibility",
            "Badges",
            "Bar Codes",
            "Benchmarking",
            "Bitmaps",
            "Bluetooth",
            "Blur Effects",
            "Bread Crumbs",
            "BRMS",
            "Browser Extensions",
            "Build Systems",
            "Bundles",
            "Buttons",
            "Caching",
            "Camera",
            "Canvas",
            "Cards",
            "Carousels",
            "Changelog",
            "Checkboxes",
            "Cloud Storages",
            "Color Analysis",
            "Color Pickers",
            "Colors",
            "Comet/Push",
            "Compass Sensors",
            "Content Providers",
            "Crash Reports",
            "Credit Cards",
            "Credits",
            "CSV",
            "Curl/Flip Effects",
            "Data Binding",
            "Data Generators",
            "Data Structures",
            "Database",
            "Database Browsers",
            "Date & Time Pickers",
            "Debugging",
            "Decompilers",
            "Deep Links",
            "Dependency Injections",
            "Design",
            "Design Patterns",
            "Dex",
            "Dialogs",
            "Distributed Computing",
            "Distribution Platforms",
            "Download Managers",
            "Drawables",
            "Emoji",
            "Emulators",
            "EPUB",
            "Equalizers & Visualizations",
            "Event Buses",
            "Exception Handling",
            "Face Recognition",
            "Feedback & Ratings",
            "File System",
            "File/Directory Choosers",
            "Fingerprint",
            "Floating Action Buttons",
            "Fonts",
            "Forms",
            "Fragments",
            "FRP",
            "FSM",
            "Functional Programming",
            "Gamepads",
            "Games",
            "Gestures",
            "GIF",
            "Glow Pad Views",
            "Gradle Plugins",
            "Graphics",
            "Grid Views",
            "Highlighting",
            "HTML",
            "HTTP Mocking",
            "Icons",
            "IDE",
            "IDE Plugins",
            "Image Croppers",
            "Image Loaders",
            "Image Pickers",
            "Image Processing",
            "Image Views",
            "Instrumentation",
            "Intents",
            "Job Schedulers",
            "JSON",
            "Keyboard",
            "Kotlin",
            "Layouts",
            "List View",
            "List Views",
            "Localization",
            "Location",
            "Lock Patterns",
            "Logcat",
            "Logging",
            "Mails",
            "Maps",
            "Markdown",
            "Mathematics",
            "Maven Plugins",
            "MBaaS",
            "Media",
            "Menus",
            "Messaging",
            "MIME",
            "Mobile Web Frameworks",
            "Native Image Processing",
            "Navigation",
            "NDK",
            "Networking",
            "NFC",
            "NoSQL",
            "Number Pickers",
            "OAuth",
            "Object Mocking",
            "OCR Engines",
            "OpenGL",
            "ORM",
            "Other Pickers",
            "Parallax List Views",
            "Parcelables",
            "Particle Systems",
            "Password Inputs",
            "PDF",
            "Permissions",
            "Physics Engines",
            "Platforms",
            "Plugin Frameworks",
            "Preferences",
            "Progress Indicators",
            "ProGuard",
            "Properties",
            "Protocol Buffer",
            "Pull To Refresh",
            "Purchases",
            "Push/Pull Notifications",
            "QR Codes",
            "Quick Return",
            "Radio Buttons",
            "Range Bars",
            "Ratings",
            "Recycler Views",
            "Resources",
            "REST",
            "Ripple Effects",
            "RSS",
            "Screenshots",
            "Scripting",
            "Scroll Views",
            "SDK",
            "Search Inputs",
            "Security",
            "Sensors",
            "Services",
            "Showcase Views",
            "Signatures",
            "Sliding Panels",
            "Snackbars",
            "SOAP",
            "Social Networks",
            "Spannable",
            "Spinners",
            "Splash Screens",
            "SSH",
            "Static Analysis Tools",
            "Status Bars",
            "Styling",
            "SVG",
            "System",
            "Tags",
            "TDD & BDD",
            "Template Engines",
            "Testing",
            "Testing Tools",
            "Text Formatting",
            "Text Views",
            "Text Watchers",
            "Text-to-Speech",
            "Toasts",
            "Toolkits For Other PL",
            "Tools",
            "Tooltips",
            "TV",
            "Updaters",
            "USB",
            "Utils",
            "Validation",
            "Video",
            "View Adapters",
            "View Pagers",
            "Views",
            "Watch Face",
            "Wearable Data Layer",
            "Weather",
            "Web Tools",
            "Web Views",
            "WebRTC",
            "WebSockets",
            "Wheel Widgets",
            "Wi-Fi",
            "Widgets",
            "Windows",
            "Wizards",
            "XML",
            "XMPP",
            "YAML",
            "ZIP Codes"};
    public static final String[] data1 = {"2D引擎",
            "3D引擎",
            "9-贴片",
            "行动酒吧",
            "活动",
            "亚行",
            "广告",
            "分析",
            "动画",
            "ANR",
            "AOP",
            "API",
            "APK",
            "易于",
            "建筑",
            "音频",
            "自动完成",
            "后台处理",
            "向后兼容性",
            "徽章",
            "条码",
            "标杆",
            "位图",
            "蓝牙",
            "模糊效果",
            "面包屑",
            "BRMS",
            "浏览器扩展",
            "构建系统",
            "捆绑",
            "纽扣",
            "缓存",
            "相机",
            "帆布",
            "牌",
            "旋转木马",
            "更新日志",
            "复选框",
            "云存储",
            "颜色分析",
            "拾色机",
            "颜色",
            "彗星/推",
            "指南针传感器",
            "内容提供商",
            "崩溃报告",
            "信用卡",
            "信用",
            "CSV",
            "卷曲/翻转效果",
            "数据绑定",
            "数据发生器",
            "数据结构",
            "数据库",
            "数据库浏览器",
            "日期和时间选择者",
            "调试",
            "反编译",
            "深度链接",
            "依赖注入",
            "设计",
            "设计模式",
            "地塞米松",
            "对话框",
            "分布式计算",
            "分销平台",
            "下载管理员",
            "可绘制区域",
            "绘文字",
            "模拟器",
            "EPUB",
            "均衡与可视化",
            "事件巴士",
            "异常处理",
            "人脸识别",
            "反馈与评级",
            "文件系统",
            "文件/目录选择器",
            "指纹",
            "浮动动作按钮",
            "字体",
            "形式",
            "碎片",
            "玻璃钢",
            "FSM",
            "功能编程",
            "Gamepads",
            "游戏",
            "手势",
            "GIF",
            "发光垫意见",
            "Gradle Plugins",
            "图形",
            "网格视图",
            "三顾茅庐",
            "HTML",
            "HTTP Mocking",
            "图标",
            "IDE",
            "IDE插件",
            "Image Croppers",
            "图像装载机",
            "图像选择器",
            "图像处理",
            "图像视图",
            "仪器仪表",
            "意图",
            "Job Schedulers",
            "JSON",
            "键盘",
            "科特林",
            "布局",
            "列表显示",
            "列表视图",
            "本土化",
            "位置",
            "锁定模式",
            "logcat的",
            "记录",
            "邮件",
            "地图",
            "降价",
            "数学",
            "Maven插件",
            "MBaaS",
            "媒体",
            "菜单",
            "消息",
            "哑剧",
            "移动Web框架",
            "本地图像处理",
            "导航",
            "NDK",
            "联网",
            "NFC",
            "NoSQL的",
            "数字选择器",
            "OAuth的",
            "对象嘲笑",
            "OCR引擎",
            "OpenGL的",
            "ORM",
            "其他选手",
            "视差列表视图",
            "Parcelables并",
            "粒子系统",
            "密码输入",
            "PDF",
            "权限",
            "物理引擎",
            "平台",
            "插件框架",
            "优先",
            "进度指标",
            "ProGuard的",
            "属性",
            "协议缓冲区",
            "拉扯刷新",
            "购买",
            "推/拉通知",
            "QR码",
            "快回",
            "无线电按钮",
            "范围酒吧",
            "评分",
            "回收者意见",
            "资源",
            "休息",
            "波纹效应",
            "RSS",
            "截图",
            "脚本",
            "滚动视图",
            "SDK",
            "搜索输入",
            "安全",
            "传感器",
            "服务",
            "展示观点",
            "签名",
            "滑板",
            "小吃店",
            "肥皂",
            "社交网络",
            "Spannable",
            "纱厂",
            "闪屏",
            "SSH",
            "静态分析工具",
            "状态栏",
            "造型",
            "SVG",
            "系统",
            "标签",
            "TDD＆BDD",
            "模板引擎",
            "测试",
            "测试工具",
            "文本格式",
            "文字观点",
            "文本观察者",
            "文字转语音",
            "干杯",
            "其他PL的工具包",
            "工具",
            "工具提示",
            "电视",
            "更新程序",
            "USB",
            "utils的",
            "验证",
            "视频",
            "查看适配器",
            "查看寻呼机",
            "意见",
            "看脸",
            "可穿戴数据层",
            "天气",
            "Web工具",
            "网页浏览",
            "的WebRTC",
            "WebSockets的",
            "轮小部件",
            "无线上网",
            "部件",
            "视窗",
            "奇才",
            "XML",
            "XMPP",
            "YAML",
            "邮政编码"};
}

